name: Bump Version
on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string

jobs:
  create-release:
    name: Bump Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
          with:
            ref: master

      - name: Version Bump
        run: npm version ${{ inputs.type }} -m "Release v%s (${{ inputs.type }})"

      - name: Push Bump
        run: git push && git push --tags
